hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.connection.driver_class=org.postgresql.Driver
hibernate.connection.url=jdbc:postgresql://localhost:12345/homework12
hibernate.connection.username=postgres
hibernate.connection.password=123
hibernate.connection.pool_size=9
hibernate.connection.autocommit=true